javascript_compressor: yui
gzip_assets: off

javascripts:
  common:
    - public/assets/javascripts/application.js

stylesheets:
  common:
    - public/stylesheets/base.css
    - public/stylesheets/skeleton.css
    - public/stylesheets/layout.css
    - public/stylesheets/application.css

